trend_spotting_task:
  description: >
    Analyze current social media trends and viral content patterns related to {topic}.
    Identify emerging discussions, controversies, and viral-worthy angles.
    Consider audience engagement patterns and viral potential indicators.
  expected_output: >
    A detailed analysis of 5-7 trending topics/angles related to {topic}, including:
    - Current engagement metrics and growth trajectory
    - Key audience demographics and interests
    - Viral potential assessment
    - Recommended content angles
  agent: trend_spotter

hook_creation_task:
  description: >
    Create 3-5 compelling hooks for each trending topic identified.
    Focus on scroll-stopping first lines that grab attention instantly.
    Ensure hooks are relatable and spark curiosity.
  expected_output: >
    For each trending topic:
    - 3-5 unique hook variations
    - Explanation of psychological triggers used
    - Target audience resonance points
  agent: hook_creator

content_drafting_task:
  description: >
    Transform the trending topics and hooks into engaging, conversational content.
    Break down complex aspects of {topic} into digestible chunks.
    Maintain a natural, relatable tone throughout.
  expected_output: >
    For each topic:
    - Full content draft (500-800 words)
    - Key takeaways and learning points
    - Suggested engagement prompts
  agent: content_drafter

final_editing_task:
  description: >
    Polish and optimize all content pieces for maximum impact.
    Add appropriate emojis, formatting, and structure improvements.
    Ensure content is visually appealing and easy to consume.
  expected_output: >
    Final versions of all content pieces with:
    - Strategic emoji placement
    - Optimized formatting and structure
    - Enhanced visual appeal elements
    - Platform-specific formatting recommendations
  agent: final_editor
